"""Gitee PR creation after successful CI pipeline."""

import logging

from integrations.gitee_client import GiteeClient

logger = logging.getLogger(__name__)


def push_and_create_pr(repo_path, branch_name, parsed_stack, source_info,
                       ci_result, config, tools, resolve_env_fn):
    """Push branch to remote and create a Gitee PR.

    Returns dict: {pr_created: bool, pr_url: str, pr_number: int, error: str}
    """
    result = {'pr_created': False, 'pr_url': '', 'pr_number': None, 'error': None}

    gitee_cfg = config.get('gitee', {}) or {}
    if not gitee_cfg.get('enabled', False):
        result['error'] = 'Gitee integration not enabled'
        return result

    owner = gitee_cfg.get('owner', '')

    repo = gitee_cfg.get('repo', '')
    if not owner or not repo:
        remote_url = tools['git_manager'].get_remote_url(repo_path)
        parsed_owner, parsed_repo = tools['git_manager'].parse_gitee_owner_repo(remote_url)
        owner = owner or parsed_owner
        repo = repo or parsed_repo

    if not owner or not repo:
        result['error'] = 'Could not determine Gitee owner/repo. Configure gitee.owner and gitee.repo in config.yml'
        return result

    pushed = tools['git_manager'].push_branch(repo_path, branch_name)
    if not pushed:
        result['error'] = 'Failed to push branch to remote'
        return result

    token_env = gitee_cfg.get('access_token_env', 'GITEE_TOKEN')
    access_token = resolve_env_fn(token_env)
    if not access_token:
        result['error'] = 'Gitee access token not configured (set access_token_env)'
        return result

    gitee_client = GiteeClient(
        access_token=access_token,
        base_url=gitee_cfg.get('api_base_url', 'https://gitee.com/api/v5')
    )

    exception_type = parsed_stack[0].get('exception_type', 'Exception') if parsed_stack else 'Exception'
    class_name = source_info.get('class_name', 'unknown') if source_info else 'unknown'
    title_template = gitee_cfg.get('pr_title_template', 'fix: auto-fix {exception_type} in {class_name}')
    title = title_template.format(exception_type=exception_type, class_name=class_name)

    body_lines = [
        '## Auto-Fix PR',
        '',
        'This PR was automatically generated by auto-fix-agent.',
        '',
        '### Exception',
        '```',
        parsed_stack[0].get('exception_type', 'Unknown') if parsed_stack else 'Unknown',
        '```',
        '',
        '### CI Pipeline',
    ]
    for stage in ci_result.get('stages_passed', []):
        body_lines.append('- [OK] %s' % stage)
    for stage in ci_result.get('stages_failed', []):
        body_lines.append('- [FAIL] %s' % stage)
    body = '\n'.join(body_lines)

    target_branch = gitee_cfg.get('target_branch', 'main')

    pr_result = gitee_client.create_pull_request(
        owner=owner, repo=repo, title=title,
        head=branch_name, base=target_branch, body=body
    )

    result['pr_created'] = pr_result['success']
    result['pr_url'] = pr_result.get('url', '')
    result['pr_number'] = pr_result.get('number')
    result['error'] = pr_result.get('error')

    return result
